export type ThemeTokens = {
  '--vg-bg': string
  '--vg-surface': string
  '--vg-surface-2': string
  '--vg-ink': string
  '--vg-ink-soft': string
  '--vg-muted': string
  '--vg-line': string
  '--vg-brand': string
  '--vg-brand-press': string
  '--vg-accent': string
  '--vg-on-brand': string
  '--vg-on-accent': string
  '--vg-cta-bg': string
  '--vg-cta-ink': string
  '--vg-hero-bg': string
  '--vg-hero-ink': string
  '--vg-hero-eyebrow': string
  '--vg-hero-accent'?: string
  '--vg-bar-bg': string
  '--vg-bar-ink': string
  '--vg-frame-back': string
  '--vg-frame-radius': string
  '--vg-font-display': string
  '--vg-font-body': string
  '--vg-radius': string
  '--vg-radius-sm': string
  '--vg-radius-btn': string
  '--vg-shadow': string
  '--vg-shadow-sm': string
  '--vg-display-spacing': string
  '--vg-h1-weight': string
}

export type ThemeKey =
  | 'warm-bronze'
  | 'trust-navy'
  | 'quiet-luxe'
  | 'coral-midnight'
  | 'azure-cloud'
  | 'forest-clay'
  | 'sky-blue'
  | 'lilac-bright'
  | 'sunburst'
  | 'mint-blush'
  | 'pop-art'
  | 'mint-modern'
  | 'editorial-paper'
  | 'bold-confident'
  | 'emerald-brass'
  | 'peach-warm'

export const themes: Record<ThemeKey, { name: string; tokens: ThemeTokens }> = {
  'warm-bronze': {
    name: '02 · Warm Bronze & Espresso',
    tokens: {
      '--vg-bg': '#F3E9D7',
      '--vg-surface': '#FDF6EC',
      '--vg-surface-2': '#EAD9BF',
      '--vg-ink': '#2E2620',
      '--vg-ink-soft': '#5C4A3A',
      '--vg-muted': '#8C7460',
      '--vg-line': '#DDD0B8',
      '--vg-brand': '#9A6A3C',
      '--vg-brand-press': '#7A5230',
      '--vg-accent': '#B8854F',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#FFFFFF',
      '--vg-cta-bg': '#9A6A3C',
      '--vg-cta-ink': '#FFFFFF',
      '--vg-hero-bg': '#F3E9D7',
      '--vg-hero-ink': '#2E2620',
      '--vg-hero-eyebrow': '#9A6A3C',
      '--vg-hero-accent': '#B8854F',
      '--vg-bar-bg': '#2E2620',
      '--vg-bar-ink': '#F3E9D7',
      '--vg-frame-back': '#B8854F',
      '--vg-frame-radius': '24px',
      '--vg-font-display': "'Lora', Georgia, serif",
      '--vg-font-body': "'Inter', system-ui, sans-serif",
      '--vg-radius': '12px',
      '--vg-radius-sm': '6px',
      '--vg-radius-btn': '13px',
      '--vg-shadow': '0 4px 24px rgba(46,38,32,0.10)',
      '--vg-shadow-sm': '0 2px 8px rgba(46,38,32,0.07)',
      '--vg-display-spacing': '-0.02em',
      '--vg-h1-weight': '600',
    },
  },
  'trust-navy': {
    name: '01 · Trust Navy & Sage',
    tokens: {
      '--vg-bg': '#F4F1EA',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#E8E3D8',
      '--vg-ink': '#16263D',
      '--vg-ink-soft': '#2D4A6E',
      '--vg-muted': '#5A7394',
      '--vg-line': '#D4CEBC',
      '--vg-brand': '#16263D',
      '--vg-brand-press': '#0D1929',
      '--vg-accent': '#5C8268',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#FFFFFF',
      '--vg-cta-bg': '#16263D',
      '--vg-cta-ink': '#FFFFFF',
      '--vg-hero-bg': '#16263D',
      '--vg-hero-ink': '#FFFFFF',
      '--vg-hero-eyebrow': '#5C8268',
      '--vg-bar-bg': '#5C8268',
      '--vg-bar-ink': '#FFFFFF',
      '--vg-frame-back': '#5C8268',
      '--vg-frame-radius': '20px',
      '--vg-font-display': "'Bricolage Grotesque', 'Inter', sans-serif",
      '--vg-font-body': "'Inter', system-ui, sans-serif",
      '--vg-radius': '10px',
      '--vg-radius-sm': '5px',
      '--vg-radius-btn': '10px',
      '--vg-shadow': '0 4px 24px rgba(22,38,61,0.12)',
      '--vg-shadow-sm': '0 2px 8px rgba(22,38,61,0.08)',
      '--vg-display-spacing': '-0.03em',
      '--vg-h1-weight': '700',
    },
  },
  'quiet-luxe': {
    name: '03 · Quiet Luxe — Monochrome & Gold',
    tokens: {
      '--vg-bg': '#FAF9F6',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#F0EEE9',
      '--vg-ink': '#1A1A1A',
      '--vg-ink-soft': '#3D3D3D',
      '--vg-muted': '#6B6B6B',
      '--vg-line': '#E0DDD6',
      '--vg-brand': '#1A1A1A',
      '--vg-brand-press': '#000000',
      '--vg-accent': '#B7942F',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#FFFFFF',
      '--vg-cta-bg': '#B7942F',
      '--vg-cta-ink': '#FFFFFF',
      '--vg-hero-bg': '#1A1A1A',
      '--vg-hero-ink': '#FAF9F6',
      '--vg-hero-eyebrow': '#B7942F',
      '--vg-bar-bg': '#1A1A1A',
      '--vg-bar-ink': '#FAF9F6',
      '--vg-frame-back': '#B7942F',
      '--vg-frame-radius': '4px',
      '--vg-font-display': "'Crimson Pro', 'Georgia', serif",
      '--vg-font-body': "'Inter', system-ui, sans-serif",
      '--vg-radius': '4px',
      '--vg-radius-sm': '2px',
      '--vg-radius-btn': '4px',
      '--vg-shadow': '0 4px 24px rgba(0,0,0,0.10)',
      '--vg-shadow-sm': '0 2px 8px rgba(0,0,0,0.06)',
      '--vg-display-spacing': '-0.01em',
      '--vg-h1-weight': '400',
    },
  },
  'coral-midnight': {
    name: 'Coral & Midnight',
    tokens: {
      '--vg-bg': '#FBF1E6',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#F2E4CE',
      '--vg-ink': '#27314F',
      '--vg-ink-soft': '#3D4E72',
      '--vg-muted': '#6678A0',
      '--vg-line': '#E0D4BC',
      '--vg-brand': '#F1543F',
      '--vg-brand-press': '#D03D2A',
      '--vg-accent': '#F6B33F',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#27314F',
      '--vg-cta-bg': '#F1543F',
      '--vg-cta-ink': '#FFFFFF',
      '--vg-hero-bg': '#27314F',
      '--vg-hero-ink': '#FFFFFF',
      '--vg-hero-eyebrow': '#F6B33F',
      '--vg-hero-accent': '#F6B33F',
      '--vg-bar-bg': '#0E7C8B',
      '--vg-bar-ink': '#FFFFFF',
      '--vg-frame-back': '#F6B33F',
      '--vg-frame-radius': '46% 54% 58% 42% / 54% 44% 56% 46%',
      '--vg-font-display': "'Bricolage Grotesque', 'Inter', sans-serif",
      '--vg-font-body': "'Inter', system-ui, sans-serif",
      '--vg-radius': '14px',
      '--vg-radius-sm': '8px',
      '--vg-radius-btn': '999px',
      '--vg-shadow': '0 4px 24px rgba(39,49,79,0.12)',
      '--vg-shadow-sm': '0 2px 8px rgba(39,49,79,0.08)',
      '--vg-display-spacing': '-0.02em',
      '--vg-h1-weight': '700',
    },
  },
  'azure-cloud': {
    name: 'Azure & Cloud',
    tokens: {
      '--vg-bg': '#E3E7EF',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#D0D6E4',
      '--vg-ink': '#16356B',
      '--vg-ink-soft': '#2A4E8C',
      '--vg-muted': '#4E6FA0',
      '--vg-line': '#C0C8D8',
      '--vg-brand': '#1F6FD6',
      '--vg-brand-press': '#1558B0',
      '--vg-accent': '#F5D416',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#16356B',
      '--vg-cta-bg': '#F5D416',
      '--vg-cta-ink': '#16356B',
      '--vg-hero-bg': '#E3E7EF',
      '--vg-hero-ink': '#16356B',
      '--vg-hero-eyebrow': '#1F6FD6',
      '--vg-bar-bg': '#16356B',
      '--vg-bar-ink': '#FFFFFF',
      '--vg-frame-back': '#1F6FD6',
      '--vg-frame-radius': '8px',
      '--vg-font-display': "'Instrument Sans', 'Inter', sans-serif",
      '--vg-font-body': "'Inter', system-ui, sans-serif",
      '--vg-radius': '10px',
      '--vg-radius-sm': '5px',
      '--vg-radius-btn': '8px',
      '--vg-shadow': '0 4px 24px rgba(22,53,107,0.12)',
      '--vg-shadow-sm': '0 2px 8px rgba(22,53,107,0.08)',
      '--vg-display-spacing': '-0.02em',
      '--vg-h1-weight': '700',
    },
  },
  'forest-clay': {
    name: 'Forest & Clay',
    tokens: {
      '--vg-bg': '#F4F1E9',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#E8E3D4',
      '--vg-ink': '#1D2E26',
      '--vg-ink-soft': '#314C3F',
      '--vg-muted': '#5A7A6A',
      '--vg-line': '#D4CCBA',
      '--vg-brand': '#314C3F',
      '--vg-brand-press': '#203328',
      '--vg-accent': '#D98E73',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#FFFFFF',
      '--vg-cta-bg': '#D98E73',
      '--vg-cta-ink': '#FFFFFF',
      '--vg-hero-bg': '#2E4039',
      '--vg-hero-ink': '#FFFFFF',
      '--vg-hero-eyebrow': '#D98E73',
      '--vg-hero-accent': '#D98E73',
      '--vg-bar-bg': '#314C3F',
      '--vg-bar-ink': '#FFFFFF',
      '--vg-frame-back': '#D98E73',
      '--vg-frame-radius': '999px',
      '--vg-font-display': "'Libre Baskerville', 'Georgia', serif",
      '--vg-font-body': "'Inter', system-ui, sans-serif",
      '--vg-radius': '12px',
      '--vg-radius-sm': '6px',
      '--vg-radius-btn': '999px',
      '--vg-shadow': '0 4px 24px rgba(30,46,38,0.10)',
      '--vg-shadow-sm': '0 2px 8px rgba(30,46,38,0.06)',
      '--vg-display-spacing': '-0.01em',
      '--vg-h1-weight': '400',
    },
  },
  'sky-blue': {
    name: '09 · Sky Blue — Professional Trust',
    tokens: {
      '--vg-bg': '#EAF3FC',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#D8EAFF',
      '--vg-ink': '#123B7A',
      '--vg-ink-soft': '#1957BF',
      '--vg-muted': '#5E7BA3',
      '--vg-line': '#CFE3FA',
      '--vg-brand': '#2F6FED',
      '--vg-brand-press': '#1957BF',
      '--vg-accent': '#2F6FED',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#FFFFFF',
      '--vg-cta-bg': '#2F6FED',
      '--vg-cta-ink': '#FFFFFF',
      '--vg-hero-bg': '#EAF3FC',
      '--vg-hero-ink': '#123B7A',
      '--vg-hero-eyebrow': '#1957BF',
      '--vg-hero-accent': '#2F6FED',
      '--vg-bar-bg': '#123B7A',
      '--vg-bar-ink': '#FFFFFF',
      '--vg-frame-back': '#BFE0FF',
      '--vg-frame-radius': '22px',
      '--vg-font-display': "'Space Grotesk', 'Inter', sans-serif",
      '--vg-font-body': "'Inter', system-ui, sans-serif",
      '--vg-radius': '14px',
      '--vg-radius-sm': '8px',
      '--vg-radius-btn': '10px',
      '--vg-shadow': '0 8px 24px rgba(47,111,237,0.16)',
      '--vg-shadow-sm': '0 2px 8px rgba(47,111,237,0.10)',
      '--vg-display-spacing': '-0.02em',
      '--vg-h1-weight': '700',
    },
  },
  'lilac-bright': {
    name: '10 · Lilac Bright — Modern SaaS',
    tokens: {
      '--vg-bg': '#F5F1FF',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#EAE0FF',
      '--vg-ink': '#2A1854',
      '--vg-ink-soft': '#5C4A85',
      '--vg-muted': '#8677AE',
      '--vg-line': '#ECE4FF',
      '--vg-brand': '#7C5CFC',
      '--vg-brand-press': '#6543E0',
      '--vg-accent': '#FF5FA2',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#FFFFFF',
      '--vg-cta-bg': '#7C5CFC',
      '--vg-cta-ink': '#FFFFFF',
      '--vg-hero-bg': '#F5F1FF',
      '--vg-hero-ink': '#2A1854',
      '--vg-hero-eyebrow': '#7C5CFC',
      '--vg-hero-accent': '#FF5FA2',
      '--vg-bar-bg': '#2A1854',
      '--vg-bar-ink': '#FFFFFF',
      '--vg-frame-back': '#C9B6FF',
      '--vg-frame-radius': '20px',
      '--vg-font-display': "'Space Grotesk', 'Inter', sans-serif",
      '--vg-font-body': "'Inter', system-ui, sans-serif",
      '--vg-radius': '18px',
      '--vg-radius-sm': '10px',
      '--vg-radius-btn': '999px',
      '--vg-shadow': '0 8px 26px rgba(124,92,252,0.18)',
      '--vg-shadow-sm': '0 2px 10px rgba(124,92,252,0.10)',
      '--vg-display-spacing': '-0.03em',
      '--vg-h1-weight': '700',
    },
  },
  sunburst: {
    name: '11 · Sunburst — Creative Rainbow',
    tokens: {
      '--vg-bg': '#FFF7ED',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#FFCF56',
      '--vg-ink': '#20201C',
      '--vg-ink-soft': '#2E2A24',
      '--vg-muted': '#4A463E',
      '--vg-line': '#EADFC8',
      '--vg-brand': '#20201C',
      '--vg-brand-press': '#000000',
      '--vg-accent': '#FF5A7A',
      '--vg-on-brand': '#FFCF56',
      '--vg-on-accent': '#FFFFFF',
      '--vg-cta-bg': '#20201C',
      '--vg-cta-ink': '#FFCF56',
      '--vg-hero-bg': '#FFCF56',
      '--vg-hero-ink': '#20201C',
      '--vg-hero-eyebrow': '#FF5A7A',
      '--vg-hero-accent': '#FF5A7A',
      '--vg-bar-bg': '#20201C',
      '--vg-bar-ink': '#FFCF56',
      '--vg-frame-back': '#FF7A6B',
      '--vg-frame-radius': '16px',
      '--vg-font-display': "'Archivo', sans-serif",
      '--vg-font-body': "'Plus Jakarta Sans', system-ui, sans-serif",
      '--vg-radius': '10px',
      '--vg-radius-sm': '6px',
      '--vg-radius-btn': '999px',
      '--vg-shadow': '0 8px 24px rgba(32,32,28,0.16)',
      '--vg-shadow-sm': '0 2px 8px rgba(32,32,28,0.10)',
      '--vg-display-spacing': '-0.02em',
      '--vg-h1-weight': '800',
    },
  },
  'mint-blush': {
    name: '12 · Mint & Blush — Soft Professional',
    tokens: {
      '--vg-bg': '#F7FBF9',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#DCF2E9',
      '--vg-ink': '#22423A',
      '--vg-ink-soft': '#5A7A70',
      '--vg-muted': '#7C9D91',
      '--vg-line': '#DCEFE6',
      '--vg-brand': '#6FC7A8',
      '--vg-brand-press': '#57B393',
      '--vg-accent': '#F3C6D2',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#22423A',
      '--vg-cta-bg': '#6FC7A8',
      '--vg-cta-ink': '#FFFFFF',
      '--vg-hero-bg': '#F7FBF9',
      '--vg-hero-ink': '#22423A',
      '--vg-hero-eyebrow': '#2C8067',
      '--vg-hero-accent': '#6FC7A8',
      '--vg-bar-bg': '#22423A',
      '--vg-bar-ink': '#FFFFFF',
      '--vg-frame-back': '#F3C6D2',
      '--vg-frame-radius': '24px',
      '--vg-font-display': "'Plus Jakarta Sans', system-ui, sans-serif",
      '--vg-font-body': "'Plus Jakarta Sans', system-ui, sans-serif",
      '--vg-radius': '16px',
      '--vg-radius-sm': '8px',
      '--vg-radius-btn': '14px',
      '--vg-shadow': '0 8px 22px rgba(34,66,58,0.10)',
      '--vg-shadow-sm': '0 2px 8px rgba(34,66,58,0.06)',
      '--vg-display-spacing': '-0.02em',
      '--vg-h1-weight': '700',
    },
  },
  'pop-art': {
    name: '13 · Pop Art — Bright Playful',
    tokens: {
      '--vg-bg': '#FFE156',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#FFF3B0',
      '--vg-ink': '#141414',
      '--vg-ink-soft': '#3A362E',
      '--vg-muted': '#3A362E',
      '--vg-line': '#141414',
      '--vg-brand': '#3A86FF',
      '--vg-brand-press': '#1F5FD1',
      '--vg-accent': '#FF5D8F',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#FFFFFF',
      '--vg-cta-bg': '#3A86FF',
      '--vg-cta-ink': '#FFFFFF',
      '--vg-hero-bg': '#FFE156',
      '--vg-hero-ink': '#141414',
      '--vg-hero-eyebrow': '#FF5D8F',
      '--vg-hero-accent': '#3A86FF',
      '--vg-bar-bg': '#141414',
      '--vg-bar-ink': '#FFE156',
      '--vg-frame-back': '#FF5D8F',
      '--vg-frame-radius': '4px',
      '--vg-font-display': "'Archivo', sans-serif",
      '--vg-font-body': "'Archivo', sans-serif",
      '--vg-radius': '10px',
      '--vg-radius-sm': '4px',
      '--vg-radius-btn': '4px',
      '--vg-shadow': '4px 4px 0 #141414',
      '--vg-shadow-sm': '2px 2px 0 #141414',
      '--vg-display-spacing': '-0.02em',
      '--vg-h1-weight': '800',
    },
  },
  'mint-modern': {
    name: '04 · Mint — Modern SaaS',
    tokens: {
      '--vg-bg': '#F2F7F5',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#F7FBF9',
      '--vg-ink': '#0F2A24',
      '--vg-ink-soft': '#3C5750',
      '--vg-muted': '#5C7A72',
      '--vg-line': '#E2EFEA',
      '--vg-brand': '#14A07A',
      '--vg-brand-press': '#0E7A5C',
      '--vg-accent': '#14A07A',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#FFFFFF',
      '--vg-cta-bg': '#14A07A',
      '--vg-cta-ink': '#FFFFFF',
      '--vg-hero-bg': '#F2F7F5',
      '--vg-hero-ink': '#0F2A24',
      '--vg-hero-eyebrow': '#14A07A',
      '--vg-hero-accent': '#14A07A',
      '--vg-bar-bg': '#0F2A24',
      '--vg-bar-ink': '#FFFFFF',
      '--vg-frame-back': '#DBF0E8',
      '--vg-frame-radius': '18px',
      '--vg-font-display': "'Space Grotesk', 'Inter', sans-serif",
      '--vg-font-body': "'Inter', system-ui, sans-serif",
      '--vg-radius': '16px',
      '--vg-radius-sm': '8px',
      '--vg-radius-btn': '999px',
      '--vg-shadow': '0 8px 20px rgba(20,160,122,0.18)',
      '--vg-shadow-sm': '0 2px 8px rgba(20,160,122,0.10)',
      '--vg-display-spacing': '-0.03em',
      '--vg-h1-weight': '700',
    },
  },
  'editorial-paper': {
    name: '05 · Editorial Paper',
    tokens: {
      '--vg-bg': '#F6F3EC',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#EDE8DC',
      '--vg-ink': '#20201C',
      '--vg-ink-soft': '#4A463E',
      '--vg-muted': '#8A8276',
      '--vg-line': '#D9D2C4',
      '--vg-brand': '#B5532F',
      '--vg-brand-press': '#8E3E20',
      '--vg-accent': '#B5532F',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#FFFFFF',
      '--vg-cta-bg': '#20201C',
      '--vg-cta-ink': '#F6F3EC',
      '--vg-hero-bg': '#F6F3EC',
      '--vg-hero-ink': '#20201C',
      '--vg-hero-eyebrow': '#B5532F',
      '--vg-hero-accent': '#B5532F',
      '--vg-bar-bg': '#20201C',
      '--vg-bar-ink': '#F6F3EC',
      '--vg-frame-back': '#D9D2C4',
      '--vg-frame-radius': '4px',
      '--vg-font-display': "'Newsreader', Georgia, serif",
      '--vg-font-body': "'Newsreader', Georgia, serif",
      '--vg-radius': '4px',
      '--vg-radius-sm': '2px',
      '--vg-radius-btn': '4px',
      '--vg-shadow': '0 2px 12px rgba(32,32,28,0.08)',
      '--vg-shadow-sm': '0 1px 4px rgba(32,32,28,0.06)',
      '--vg-display-spacing': '-0.025em',
      '--vg-h1-weight': '400',
    },
  },
  'bold-confident': {
    name: '06 · Bold Confident',
    tokens: {
      '--vg-bg': '#ECEAE3',
      '--vg-surface': '#ECEAE3',
      '--vg-surface-2': '#DEDAD0',
      '--vg-ink': '#F4F1EA',
      '--vg-ink-soft': '#C8C4BA',
      '--vg-muted': '#8A8276',
      '--vg-line': '#3A3A30',
      '--vg-brand': '#F0531C',
      '--vg-brand-press': '#C73E0A',
      '--vg-accent': '#F0531C',
      '--vg-on-brand': '#141414',
      '--vg-on-accent': '#141414',
      '--vg-cta-bg': '#F0531C',
      '--vg-cta-ink': '#141414',
      '--vg-hero-bg': '#141414',
      '--vg-hero-ink': '#F4F1EA',
      '--vg-hero-eyebrow': '#F0531C',
      '--vg-hero-accent': '#F0531C',
      '--vg-bar-bg': '#F0531C',
      '--vg-bar-ink': '#141414',
      '--vg-frame-back': '#F0531C',
      '--vg-frame-radius': '0px',
      '--vg-font-display': "'Archivo', sans-serif",
      '--vg-font-body': "'Archivo', sans-serif",
      '--vg-radius': '0px',
      '--vg-radius-sm': '0px',
      '--vg-radius-btn': '0px',
      '--vg-shadow': 'none',
      '--vg-shadow-sm': 'none',
      '--vg-display-spacing': '-0.03em',
      '--vg-h1-weight': '800',
    },
  },
  'emerald-brass': {
    name: '07 · Emerald & Brass',
    tokens: {
      '--vg-bg': '#EFEBE0',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#E6E1D2',
      '--vg-ink': '#133A2E',
      '--vg-ink-soft': '#2A5442',
      '--vg-muted': '#5A6A60',
      '--vg-line': '#D8D0BE',
      '--vg-brand': '#C9A24B',
      '--vg-brand-press': '#A8842A',
      '--vg-accent': '#C9A24B',
      '--vg-on-brand': '#133A2E',
      '--vg-on-accent': '#133A2E',
      '--vg-cta-bg': '#C9A24B',
      '--vg-cta-ink': '#133A2E',
      '--vg-hero-bg': '#133A2E',
      '--vg-hero-ink': '#EFEBE0',
      '--vg-hero-eyebrow': '#C9A24B',
      '--vg-hero-accent': '#C9A24B',
      '--vg-bar-bg': '#133A2E',
      '--vg-bar-ink': '#EFEBE0',
      '--vg-frame-back': '#C9A24B',
      '--vg-frame-radius': '2px',
      '--vg-font-display': "'Cormorant Garamond', Georgia, serif",
      '--vg-font-body': "'Inter', system-ui, sans-serif",
      '--vg-radius': '2px',
      '--vg-radius-sm': '2px',
      '--vg-radius-btn': '2px',
      '--vg-shadow': '0 2px 16px rgba(19,58,46,0.12)',
      '--vg-shadow-sm': '0 1px 6px rgba(19,58,46,0.08)',
      '--vg-display-spacing': '-0.01em',
      '--vg-h1-weight': '400',
    },
  },
  'peach-warm': {
    name: '08 · Peach — Warm & Personal',
    tokens: {
      '--vg-bg': '#FBF7F0',
      '--vg-surface': '#FFFFFF',
      '--vg-surface-2': '#FFE7D6',
      '--vg-ink': '#3A2E26',
      '--vg-ink-soft': '#6A5849',
      '--vg-muted': '#8A7565',
      '--vg-line': '#F0D8C8',
      '--vg-brand': '#E07856',
      '--vg-brand-press': '#C25E3C',
      '--vg-accent': '#2E8B8B',
      '--vg-on-brand': '#FFFFFF',
      '--vg-on-accent': '#FFFFFF',
      '--vg-cta-bg': '#E07856',
      '--vg-cta-ink': '#FFFFFF',
      '--vg-hero-bg': '#FFE7D6',
      '--vg-hero-ink': '#3A2E26',
      '--vg-hero-eyebrow': '#E07856',
      '--vg-hero-accent': '#E07856',
      '--vg-bar-bg': '#3A2E26',
      '--vg-bar-ink': '#FBF7F0',
      '--vg-frame-back': '#FFD3B8',
      '--vg-frame-radius': '999px',
      '--vg-font-display': "'Plus Jakarta Sans', system-ui, sans-serif",
      '--vg-font-body': "'Plus Jakarta Sans', system-ui, sans-serif",
      '--vg-radius': '20px',
      '--vg-radius-sm': '10px',
      '--vg-radius-btn': '999px',
      '--vg-shadow': '0 4px 16px rgba(58,46,38,0.08)',
      '--vg-shadow-sm': '0 2px 8px rgba(58,46,38,0.05)',
      '--vg-display-spacing': '-0.02em',
      '--vg-h1-weight': '700',
    },
  },
}

// ← Change this one line to switch the active theme across the entire site
export const activeTheme: ThemeKey = 'warm-bronze'
